### ISSUE TITLE
Customization of front end 

### ISSUE THREAD

**Issue by neowenshun** [javrasya/river-admin#11]
Is there a way for me to fiddle around with the front end of river-admin? I would wish to be able to use my own front end to have some consistency within my project

**Comment by javrasya** [comment]
Hi @neowenshun , I wish I could say yes but, river-admin is not designed to be customized to adapt to existing application lookings. It is more for administration purposes which don't need to look like part of the app that runs in. It is very hard to make it look like part of the app and also keep it generic actually but it is, of course, legal to fork it and customize it and use that one in your app instead and keep it up to date with the core changes from the originating repo.
