### ISSUE TITLE
Support for CustomUser model

### ISSUE THREAD

**Issue by agriev** [javrasya/river-admin#31]
**Is your feature request related to a problem? Please describe.**
Incompatibility with a project which already replaced User model with custom user model. Which is nowadays is a kind of good practice in django development

**Describe the solution you'd like**
replace calls for User class with get_user_model() calls

**Describe alternatives you've considered**
i would probably gonna fork and make a merge request if i may

**Additional context**

**Comment by javrasya** [comment]
Closing since #32 is supposed to fix this
