### ISSUE TITLE
django 3 support

### ISSUE THREAD

**Issue by lucilecoutouly** [javrasya/river-admin#7]
is it possible to make river-admin compatible withe django 3, specially with auth groups ...
thanks

**Comment by javrasya** [comment]
It should be supported here already as long as you use a `django-river` version that supports `Django 3.0`. Have you observed something broken with `river-admin` with `Django 3.0`

**Comment by javrasya** [comment]
Can we close this issue @lucilecoutouly if my previous comment answers your question?
